# SilkCircuit Dawn for fzf
# https://github.com/hyperb1iss/silkcircuit
#
# Generated by scripts/build from lua/silkcircuit/variants.lua.
# Do not edit by hand.

export FZF_DEFAULT_OPTS=" \
--color=fg:#2b2540,bg:#faf8ff,hl:#7e2bd5 \
--color=fg+:#1a1318,bg+:#e8e0ff,hl+:#b40077 \
--color=selected-fg:#1a1318,selected-bg:#d4c8f0,selected-hl:#b40077 \
--color=gutter:#faf8ff,query:#1a1318,disabled:#8e84a8 \
--color=info:#a88600,separator:#d4c8f0,scrollbar:#7e2bd5 \
--color=prompt:#7e2bd5,pointer:#b40077,marker:#2d8659 \
--color=spinner:#007f8e,header:#007f8e,border:#009fae \
--color=label:#5a4d6e,preview-fg:#2b2540,preview-bg:#f1ecff \
--color=preview-border:#009fae,preview-label:#007f8e"
