# SilkCircuit Soft for fzf (PowerShell)
# https://github.com/hyperb1iss/silkcircuit
#
# Generated by scripts/build from lua/silkcircuit/variants.lua.
# Do not edit by hand.

$env:FZF_DEFAULT_OPTS = @(
    "--color=fg:#f8f8f2,bg:#1a1626,hl:#e892ff"
    "--color=fg+:#ffffff,bg+:#3e3456,hl+:#ff99ff"
    "--color=selected-fg:#ffffff,selected-bg:#44475a,selected-hl:#ff99ff"
    "--color=gutter:#1a1626,query:#ffffff,disabled:#b199ff"
    "--color=info:#ffe699,separator:#44475a,scrollbar:#e892ff"
    "--color=prompt:#e892ff,pointer:#ff99ff,marker:#66ff99"
    "--color=spinner:#99ffee,header:#99ffee,border:#88ffff"
    "--color=label:#e9d5ff,preview-fg:#f8f8f2,preview-bg:#141220"
    "--color=preview-border:#88ffff,preview-label:#99ffee"
) -join " "
