# SilkCircuit Dawn for fzf (PowerShell)
# https://github.com/hyperb1iss/silkcircuit
#
# Generated by scripts/build from lua/silkcircuit/variants.lua.
# Do not edit by hand.

$env:FZF_DEFAULT_OPTS = @(
    "--color=fg:#2b2540,bg:#faf8ff,hl:#7e2bd5"
    "--color=fg+:#1a1318,bg+:#f7f4ff,hl+:#b40077"
    "--color=selected-fg:#1a1318,selected-bg:#d4c8f0,selected-hl:#b40077"
    "--color=gutter:#faf8ff,query:#1a1318,disabled:#7353a9"
    "--color=info:#796100,separator:#d4c8f0,scrollbar:#7e2bd5"
    "--color=prompt:#7e2bd5,pointer:#b40077,marker:#1d6e46"
    "--color=spinner:#006e72,header:#006e72,border:#006388"
    "--color=label:#5a4d6e,preview-fg:#2b2540,preview-bg:#f4f0ff"
    "--color=preview-border:#006388,preview-label:#006e72"
) -join " "
