# SilkCircuit Neon for fzf (PowerShell)
# https://github.com/hyperb1iss/silkcircuit
#
# Generated by scripts/build from lua/silkcircuit/variants.lua.
# Do not edit by hand.

$env:FZF_DEFAULT_OPTS = @(
    "--color=fg:#f8f8f2,bg:#12101a,hl:#e135ff"
    "--color=fg+:#ffffff,bg+:#1a162a,hl+:#ff00ff"
    "--color=selected-fg:#ffffff,selected-bg:#44475a,selected-hl:#ff00ff"
    "--color=gutter:#12101a,query:#ffffff,disabled:#9580ff"
    "--color=info:#f1fa8c,separator:#44475a,scrollbar:#e135ff"
    "--color=prompt:#e135ff,pointer:#ff00ff,marker:#50fa7b"
    "--color=spinner:#80ffea,header:#80ffea,border:#5fffff"
    "--color=label:#e9d5ff,preview-fg:#f8f8f2,preview-bg:#0a0812"
    "--color=preview-border:#5fffff,preview-label:#80ffea"
) -join " "
