# SilkCircuit Vibrant for fzf
# https://github.com/hyperb1iss/silkcircuit
#
# Generated by scripts/build from lua/silkcircuit/variants.lua.
# Do not edit by hand.

export FZF_DEFAULT_OPTS=" \
--color=fg:#f8f8f2,bg:#0f0c1a,hl:#ff00ff \
--color=fg+:#ffffff,bg+:#151026,hl+:#ff00cc \
--color=selected-fg:#ffffff,selected-bg:#3a2e5a,selected-hl:#ff00cc \
--color=gutter:#0f0c1a,query:#ffffff,disabled:#b366ff \
--color=info:#ffcc00,separator:#3a2e5a,scrollbar:#ff00ff \
--color=prompt:#ff00ff,pointer:#ff00cc,marker:#00ff66 \
--color=spinner:#00ffcc,header:#00ffcc,border:#00ffff \
--color=label:#e9d5ff,preview-fg:#f8f8f2,preview-bg:#08060f \
--color=preview-border:#00ffff,preview-label:#00ffcc"
