-- iTerm2 reads .itermcolors as an Apple XML plist, and a plist parser that
-- sniffs the first bytes of the file (Python's plistlib, for one) rejects
-- anything before the XML declaration. So this target sets comment = "none"
-- and writes the provenance banner itself, right after the declaration.
--
-- Every channel is a 0..1 float, which is what `${rgbf.<role>.<channel>}` is
-- for.

local M = {}

local KEYS = {
  { "Ansi 0 Color", "terminal_black" },
  { "Ansi 1 Color", "terminal_red" },
  { "Ansi 2 Color", "terminal_green" },
  { "Ansi 3 Color", "terminal_yellow" },
  { "Ansi 4 Color", "terminal_blue" },
  { "Ansi 5 Color", "terminal_magenta" },
  { "Ansi 6 Color", "terminal_cyan" },
  { "Ansi 7 Color", "terminal_white" },
  { "Ansi 8 Color", "terminal_bright_black" },
  { "Ansi 9 Color", "terminal_bright_red" },
  { "Ansi 10 Color", "terminal_bright_green" },
  { "Ansi 11 Color", "terminal_bright_yellow" },
  { "Ansi 12 Color", "terminal_bright_blue" },
  { "Ansi 13 Color", "terminal_bright_magenta" },
  { "Ansi 14 Color", "terminal_bright_cyan" },
  { "Ansi 15 Color", "terminal_bright_white" },
  { "Background Color", "bg" },
  { "Badge Color", "purple" },
  { "Bold Color", "fg_light" },
  { "Cursor Color", "cyan" },
  { "Cursor Guide Color", "bg_highlight" },
  { "Cursor Text Color", "bg" },
  { "Foreground Color", "fg" },
  { "Link Color", "cyan" },
  { "Selected Text Color", "fg" },
  { "Selection Color", "bg_visual" },
  { "Underline Color", "cyan" },
}

local function entry(label, role)
  local function channel(name)
    return "${rgbf." .. role .. "." .. name .. "}"
  end
  return table.concat({
    "\t<key>" .. label .. "</key>",
    "\t<dict>",
    "\t\t<key>Alpha Component</key>",
    "\t\t<real>1</real>",
    "\t\t<key>Blue Component</key>",
    "\t\t<real>" .. channel("b") .. "</real>",
    "\t\t<key>Color Space</key>",
    "\t\t<string>sRGB</string>",
    "\t\t<key>Green Component</key>",
    "\t\t<real>" .. channel("g") .. "</real>",
    "\t\t<key>Red Component</key>",
    "\t\t<real>" .. channel("r") .. "</real>",
    "\t</dict>",
  }, "\n")
end

local function build_template()
  local parts = {
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!--",
    "  ${meta.name} for iTerm2",
    "  ${meta.url}",
    "",
    "  Generated by scripts/build from lua/silkcircuit/variants.lua.",
    "  Do not edit by hand.",
    "-->",
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
      .. '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
  }
  for _, key in ipairs(KEYS) do
    parts[#parts + 1] = entry(key[1], key[2])
  end
  parts[#parts + 1] = "</dict>"
  parts[#parts + 1] = "</plist>"
  return table.concat(parts, "\n")
end

local TEMPLATE = build_template()

function M.generate(colors)
  return require("silkcircuit.extra").template(TEMPLATE, colors)
end

return M
