-- Machine-readable exports of the palette itself.
--
-- palette/silkcircuit-<variant>.json is the reference every other target is
-- checked against. The base16 and base24 schemes hand the palette to tinty,
-- stylix, and the rest of the tinted-theming ecosystem.

local M = {}

local ANSI = {
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
  "bright_black",
  "bright_red",
  "bright_green",
  "bright_yellow",
  "bright_blue",
  "bright_magenta",
  "bright_cyan",
  "bright_white",
}

local HEX6 = "^#(%x%x)(%x%x)(%x%x)$"

local function round(value)
  return math.floor(value + 0.5)
end

local function to_hsl(hex)
  local rr, gg, bb = hex:match(HEX6)
  local r, g, b = tonumber(rr, 16) / 255, tonumber(gg, 16) / 255, tonumber(bb, 16) / 255
  local max, min = math.max(r, g, b), math.min(r, g, b)
  local l = (max + min) / 2
  local h, s = 0, 0

  if max ~= min then
    local d = max - min
    s = l > 0.5 and d / (2 - max - min) or d / (max + min)
    if max == r then
      h = (g - b) / d + (g < b and 6 or 0)
    elseif max == g then
      h = (b - r) / d + 2
    else
      h = (r - g) / d + 4
    end
    h = h / 6
  end

  return round(h * 360), round(s * 100), round(l * 100)
end

local function quote(value)
  return '"' .. tostring(value):gsub('[\\"]', "\\%0") .. '"'
end

--- Hex keys of a palette, sorted so the export never reshuffles.
local function color_keys(colors)
  local keys = {}
  for key, value in pairs(colors) do
    if type(value) == "string" and value:match(HEX6) then
      keys[#keys + 1] = key
    end
  end
  table.sort(keys)
  return keys
end

--- base16 is a syntax palette: the ramp runs background to foreground, then
--- the eight accents. base06 and base07 repeat fg_light because the palette
--- has no step past it that stays readable on the dawn (light) background.
local function base16_palette(colors)
  return {
    { "base00", colors.bg },
    { "base01", colors.bg_highlight },
    { "base02", colors.bg_visual },
    { "base03", colors.comment },
    { "base04", colors.fg_dark },
    { "base05", colors.fg },
    { "base06", colors.fg_light },
    { "base07", colors.fg_light },
    { "base08", colors.red },
    { "base09", colors.orange },
    { "base0A", colors.yellow },
    { "base0B", colors.green },
    { "base0C", colors.cyan },
    { "base0D", colors.blue },
    { "base0E", colors.purple },
    { "base0F", colors.coral },
  }
end

--- base24 keeps base16's ramp and adds the two darker backgrounds plus the six
--- bright ANSI slots the spec assigns to base12 through base17.
local function base24_palette(colors)
  local palette = base16_palette(colors)
  local extra = {
    { "base10", colors.bg_dark },
    { "base11", colors.bg_darker },
    { "base12", colors.terminal_bright_red },
    { "base13", colors.terminal_bright_yellow },
    { "base14", colors.terminal_bright_green },
    { "base15", colors.terminal_bright_cyan },
    { "base16", colors.terminal_bright_blue },
    { "base17", colors.terminal_bright_magenta },
  }
  for _, entry in ipairs(extra) do
    palette[#palette + 1] = entry
  end
  return palette
end

local function scheme_yaml(system, colors, palette)
  local meta = colors.meta
  local lines = {
    "# " .. meta.name .. " (" .. system .. ") for tinted-theming builders",
    "# " .. meta.url,
    "#",
    "# Generated by scripts/build from lua/silkcircuit/variants.lua.",
    "# Do not edit by hand.",
    "",
    "system: " .. quote(system),
    "name: " .. quote(meta.name),
    "slug: " .. quote(meta.slug),
    "author: " .. quote(meta.author),
    "description: " .. quote(meta.description),
    "variant: " .. quote(meta.appearance),
    "palette:",
  }
  for _, entry in ipairs(palette) do
    lines[#lines + 1] = "  " .. entry[1] .. ": " .. quote(entry[2]:sub(2))
  end
  return table.concat(lines, "\n")
end

local function palette_json(colors)
  local meta = colors.meta
  local lines = {
    "{",
    '  "name": ' .. quote(meta.name) .. ",",
    '  "slug": ' .. quote(meta.slug) .. ",",
    '  "variant": ' .. quote(meta.variant) .. ",",
    '  "appearance": ' .. quote(meta.appearance) .. ",",
    '  "description": ' .. quote(meta.description) .. ",",
    '  "url": ' .. quote(meta.url) .. ",",
    '  "generator": "scripts/build from lua/silkcircuit/variants.lua",',
    '  "colors": {',
  }

  local keys = color_keys(colors)
  for index, key in ipairs(keys) do
    local hex = colors[key]
    local rgb = colors.rgb[key]
    local h, s, l = to_hsl(hex)
    lines[#lines + 1] = string.format(
      '    %s: { "hex": %s, "rgb": [%d, %d, %d], "hsl": [%d, %d, %d] }%s',
      quote(key),
      quote(hex),
      rgb.r,
      rgb.g,
      rgb.b,
      h,
      s,
      l,
      index < #keys and "," or ""
    )
  end

  lines[#lines + 1] = "  },"
  lines[#lines + 1] = '  "terminal": {'
  for index, slot in ipairs(ANSI) do
    lines[#lines + 1] = string.format(
      "    %s: %s%s",
      quote(slot),
      quote(colors["terminal_" .. slot]),
      index < #ANSI and "," or ""
    )
  end
  lines[#lines + 1] = "  }"
  lines[#lines + 1] = "}"

  return table.concat(lines, "\n")
end

--- Write every palette export. Returns repo-relative paths.
function M.generate(root)
  local extra = require("silkcircuit.extra")
  local dir = root .. "/palette"

  if vim.fn.isdirectory(dir) == 1 then
    for entry, kind in vim.fs.dir(dir) do
      if kind == "file" and not entry:match("%.md$") then
        vim.fn.delete(dir .. "/" .. entry)
      end
    end
  end

  local written = {}
  local function emit(relative, content)
    extra.write(root .. "/" .. relative, content)
    written[#written + 1] = relative
  end

  for _, variant in ipairs(extra.variants) do
    local colors = extra.colors(variant)
    emit("palette/silkcircuit-" .. variant .. ".json", palette_json(colors))
    emit(
      "palette/base16-silkcircuit-" .. variant .. ".yaml",
      scheme_yaml("base16", colors, base16_palette(colors))
    )
    emit(
      "palette/base24-silkcircuit-" .. variant .. ".yaml",
      scheme_yaml("base24", colors, base24_palette(colors))
    )
  end

  return written
end

return M
